services:
  - type: web
    name: mf-chatbot-backend
    runtime: python
    region: oregon
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_GEMINI_MODEL
        value: gemini-2.5-flash-lite
      - key: FRONTEND_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.12.3"
